# frozen_string_literal: true

require "date"
require_relative "tin_valid/version"
require_relative "tin_valid/austria_tin"
require_relative "tin_valid/belgium_tin"
require_relative "tin_valid/bulgaria_tin"
require_relative "tin_valid/croatia_tin"
require_relative "tin_valid/cyprus_tin"
require_relative "tin_valid/czechia_tin"
require_relative "tin_valid/denmark_tin"
require_relative "tin_valid/estonia_tin"
require_relative "tin_valid/germany_tin"
require_relative "tin_valid/greece_tin"
require_relative "tin_valid/hungary_tin"
require_relative "tin_valid/ireland_tin"
require_relative "tin_valid/latvia_tin"
require_relative "tin_valid/lithuania_tin"
require_relative "tin_valid/luxembourg_tin"
require_relative "tin_valid/malta_tin"
require_relative "tin_valid/netherlands_tin"
require_relative "tin_valid/poland_tin"
require_relative "tin_valid/portugal_tin"
require_relative "tin_valid/romania_tin"
require_relative "tin_valid/slovakia_tin"
require_relative "tin_valid/slovenia_tin"
require_relative "tin_valid/spain_tin"
require_relative "tin_valid/sweden_tin"

module TinValid; end
